export {default as Home} from "./home/Home"
export {default as Product} from "./product/Product"
export {default as Navbar} from "./navbar/Navbar"
export {default as Footer} from "./footer/Footer"
export {default as NotFound} from "./notFound/NotFound"